export enum TypeTagEnum {
  Object = '[object Object]',
  Array = '[object Array]',
  Number = '[object Number]',
  String = '[object String]',
  Boolean = '[object Boolean]',
  Function = '[object Function]',
  Symbol = '[object Symbol]',
  Null = '[object Null]',
  Undefined = '[object Undefined]',
  NaN = '[object NaN]',
  Date = '[object Date]',
  Map = '[object Map]',
  Set = '[object Set]',
  WeakMap = '[object WeakMap]',
  WeakSet = '[object WeakSet]',
}

export const TYPE_DICT = {
  [TypeTagEnum.Object]: 'object',
  [TypeTagEnum.Array]: 'array',
  [TypeTagEnum.Number]: 'number',
  [TypeTagEnum.String]: 'string',
  [TypeTagEnum.Boolean]: 'boolean',
  [TypeTagEnum.Function]: 'Function',
  [TypeTagEnum.Symbol]: 'symbol',
  [TypeTagEnum.Null]: 'null',
  [TypeTagEnum.Undefined]: 'undefined',
  [TypeTagEnum.NaN]: 'NaN',
  [TypeTagEnum.Date]: 'Date',
  [TypeTagEnum.Map]: 'Map',
  [TypeTagEnum.Set]: 'Set',
  [TypeTagEnum.WeakMap]: 'WeakMap',
  [TypeTagEnum.WeakSet]: 'WeakSet',
}
